### ISSUE TITLE
Add Option to Include Password for WPA2 Encrypted Guest WiFi in QR Code

### ISSUE THREAD

**Issue by pppaapp** [ufozone/ha-unifi-voucher#105]
hello

thank you for the great work on this custom component

 it's been incredibly useful!

I need an option to include the password for WPA2 encrypted guest WiFi in the QR code

This feature is crucial for ensuring secure access while maintaining the convenience of QR code scanning

**Comment by ufozone** [comment]
Hello,

I don't understand the use case. If the wifi is encrypted with wpa2 and password protected, the voucher is no longer needed.

The unifi core integration already has the feature you want:
https://www.home-assistant.io/integrations/unifi/#image

I don't think it would be very useful to recreate the feature in this integration.
