### ISSUE TITLE
Cannot Connect to Unifi 

### ISSUE THREAD

**Issue by Sammy-cmd** [ufozone/ha-unifi-voucher#120]
My UDM on my local network does not have an https address and I'm not sure what the port is. I've tried the default 443 and also 8443 and I'm not sure what to check on the SSL certificate checkbox.

**Comment by ufozone** [comment]
You must enter the port via which the UDM can be reached.
Leave the SSL checkbox deactivated.

**Comment by Sammy-cmd** [comment]
I never enter a port number just the local IP address when using the UDM Web GUI so I don't know what it is. I tried 80 to no avail also.

**Comment by Sammy-cmd** [comment]
Oops.. Missed this in the README

Local User Only. Set up new user and got to the next page.
