### ISSUE TITLE
The specified path to the file is invalid: absolute path is needed.

### ISSUE THREAD

**Issue by Sammy-cmd** [ufozone/ha-unifi-voucher#121]
I'm running this in VBox as a VM.

I'm new to VM's. What is the absolute path needed?

**Comment by ufozone** [comment]
The path to your own logo is only necessary if the qr code is to be used.

The logo just needs to be in a place that Home Assistant can access. It makes no sense to specify a fixed location, as there are too many different installation constellations. The folder `/config/custom_components/unifi_voucher/` is over written when the integration is updated. I recommend the persistent folder `/config/www/`.
