### ISSUE TITLE
[FR] Make the "note" field usable from an action

### ISSUE THREAD

**Issue by Riza-Aslan** [ufozone/ha-unifi-voucher#122]
Thank you for this awesome integration. Is there any chance to change the "note" field? Right now it is automatically filled with "HA-generated", but I would like to fill it with a custom input entity.

Lets say my friend Michael is there and i would like to give him a voucher for my wifi, which is valid for 1 year. But then he got strange after 3 months and I would like to delete his voucher. It would be awesome, if I could do it right from HASS but even if I would have to do it from the unifi UI, it would be okay. But I need a note, that this is the voucher used by Michael.

**Comment by ufozone** [comment]
Hi, thanks for your great idea.

We have no chance to transfer an individual note (as text) with each voucher generation via the entity types possible from HA. The best we could do was via the create service.
With my integration, I would like to enable minimalist voucher handling. This means that a user voucher that was only intended for one-time use is no longer taken into account by my integration. I don't want to move away from this principle and introduce a great deal of complexity.

how often do you create such long-running vouchers and are you forced to create them via the integration? it sounds to me like a very individual requirement to create such specialized vouchers. The available addon seems almost more suitable to me:
https://community.home-assistant.io/t/unifi-wifi-voucher-addon/232017

**Comment by Riza-Aslan** [comment]
I tried it yesterday with the create service (in YAML), but HA doesn't allow extra keys 
![image](https://github.com/user-attachments/assets/8a4fe9da-6f2c-44b6-b024-c081a7be754f)

It would be absolutely enough for me, if I could set the note with the create service. Could you make that possible? I would create an script which writes the value of an input-entity into the note key over it.

My usecase is not so special. Companys often use this method to give their employees access to a guest-wifi. If someone leaves the company, the assigned voucher is getting deleted. If not, the employee gets a new voucher for a year again. This makes sure, that even if the IT forgets to delete the voucher, it is getting invalid in max. 1 year.

Using the Unifi Hotspot Manager to delete vouchers would be no problem. But I would like to enable my wife to create vouchers for our visitors when I'm not there. To use our HA dashboard would be the easiest.

**Comment by ufozone** [comment]
The create service does not yet allow you to enter a note. Some adjustments to the source code are necessary. If the feature is requested by several people, I could implement it. but you are welcome to fork the project and then post a pull request. that might be faster.

**Comment by ufozone** [comment]
@Riza-Aslan, @sreknob, @knackrack615
You want it? You get it!

New release:
https://github.com/ufozone/ha-unifi-voucher/releases/tag/v1.4
