### ISSUE TITLE
Blueprint of the example

### ISSUE THREAD

**Issue by roccotocco** [ufozone/ha-unifi-voucher#68]
Hello, may you share the images into the Blueprint of the example
Thanks

**Comment by ufozone** [comment]
Hey @roccotocco,

I bought the image in the background for 11 euros from Shutterstock:
https://www.shutterstock.com/image-vector/wifi-network-icon-wi-fi-sign-1786570310

But that was before AI image generation was available everywhere. I once used the image description from Shutterstock as a prompt in Microsoft Image Creator and got good results ;-)
